name: janus
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - libblas=*=*_mkl
  - dvc
  - python=3
  - ipython
  - pip
  - codecov
  - flake8
  - h5py
  - numpy
  - openpyxl
  - pandas
  - pytest-cov
  - pytorch
  - seaborn
  - scikit-image
  - scikit-learn
  - torchvision
  - tqdm
  - umap-learn
  - nextflow
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
