name: janus
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - libblas=*=*_mkl
  - dvc
  - dvc-ssh
  - nbstripout
  - python=3
  - ipython
  - pip
  - codecov
  - flake8
  - h5py
  - numpy
  - openpyxl
  - pandas
  - pytest-cov
  - pytorch
  - r
  - rpy2
  - r-tidyverse
  - seaborn
  - scikit-image
  - scikit-learn
  - torchvision
  - tqdm
  - umap-learn
  - nextflow
  - jupyterlab
